
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.key -out cert.crt

# kubectl create secret tls tls-local-argo --cert=cert.crt --key=key.key -n default 

apiVersion: v1
kind: Secret
metadata:
  name: tls-local
  namespace: argo-cd
data:
  tls.crt: |
            LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVIRENDQW9TZ0F3SUJBZ0lRYWFaVGZoN1pG
            RzNwVE4rdmlwT3VXekFOQmdrcWhraUc5dzBCQVFzRkFEQlAKTVI0d0hBWURWUVFLRXhWdGEyTmxj
            blFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhFakFRQmdOVkJBc01DV3RoYkdsQQphMkZzYVRFWk1CY0dB
            MVVFQXd3UWJXdGpaWEowSUd0aGJHbEFhMkZzYVRBZUZ3MHlOREV3TVRJeE9USXpNalphCkZ3MHlO
            ekF4TVRJeU1ESXpNalphTUQweEp6QWxCZ05WQkFvVEhtMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRD
            QmoKWlhKMGFXWnBZMkYwWlRFU01CQUdBMVVFQ3d3SmEyRnNhVUJyWVd4cE1JSUJJakFOQmdrcWhr
            aUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTNMdFZmTUdNR1lTekRrNUZZUnRmR3B6eWRF
            ZnBwUUwxVzM4MmdCWVgzREFICkpRcFV5Y0g4R2xETkhIcUxrUTdGdGNzRThEcUN0T2FNMnlHa2E3
            Zi80blNjdjlIQmsrMytnN2dtVkRkOWZUajQKSytsZlRTTlR2WlZDWmE2N21lVEZaUzNVY1BvK2ZK
            bDcxUGJJbUhGekt0K01EUUl5M1JSVkZVYWpYU0l0N0VoOApaUG1sR0JIYURhMERGd0dtdUx3ZFFo
            ZjJRM1lIUW0zTG9GVzFUYk9rTlJETlFHemorQjU0SXRVN2dYdFgyTjFOCjRuRFE1Y3A4dzcwdGJB
            OVBuUThWY1l4OTlBVGFMRS9rWFBuWllSSGhLR1lIZWUrWkhVaTV4cGdVaDZFZG9mM2EKdmM0NUNJ
            Q1diWEpiV3dhTTk1cS9CTDJaYnAycWNxUUlDNS9ZSnF4ZG53SURBUUFCbzRHRk1JR0NNQTRHQTFV
            ZApEd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBZkJnTlZIU01FR0RB
            V2dCUXdNZUJMCjBjbXZ4TXZWQ3VOMko0cFhnclNOcXpBNkJnTlZIUkVFTXpBeGdneGhjbWR2WTJR
            dWJHOWpZV3lDQ1d4dlkyRnMKYUc5emRJY0Vmd0FBQVljUUFBQUFBQUFBQUFBQUFBQUFBQUFBQVRB
            TkJna3Foa2lHOXcwQkFRc0ZBQU9DQVlFQQpWWXo1NkxxZElFMFRueW5mNzJCNzZaMzllUERiYlRa
            Mm1YcEt5K3Vpc1VYeUNNVHU4OE1rZmdzVytxaFROU3ZWCkljZC93TFJwemMzMlRJZWVPdldIeERs
            dGs1TTdnZkcydEVYbThRazhhS09Qa3BYb2VIMFE3aWJnQ3pIVy9qT3IKVTlTQnJJT3FmTlRDbDFP
            dFFFT0lkdVRpelR1L3Nsc3RNRENiMTZMUTdFWG5VQ21MRnRoU2FpYlVJN3ZZekU3SwpYWklzelRu
            TU9BSVZ4dFkxcUp1VkF0aGJDSngzeVNXYkN5dnpzYlBpMyt1eFFaN1M2K3pQTVNzOTZTT3FsR3JT
            CnFlVGdCNWFFQXl5S3ZLUGZkeXgyWlFCdVJ0R3I3aU82TGRScm1QNTMxT2x4K2ttZS9pYUJHaURx
            TWxtNHdYWXkKTnRjNjFyZnhkbG5UMlhEbjRZOHJYb0hBYzdwZ2FnYWMxcHZ1YlNMbThibkdxaTVo
            QWVXN2o1eEJ2SkVQZ0cxVwpUc0tTd09CcWlUbENsNmIrNjFYbXVIUDFvbUpWRHFoNytwNncvaWcy
            aE9NaDc0ZkFSM3FtM1A4S1hBN21LcW94CnlKOWFSelIxSjRTQzBQS3dwVi9WVzFyY1VTZGhUOGRa
            UTBXd0dIODNtaHFyRUFNRk9DVFhaa3JZYk5vV1RtNFMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
            LQo=
  tls.key: |
            LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
            QVNDQktjd2dnU2pBZ0VBQW9JQkFRRGN1MVY4d1l3WmhMTU8KVGtWaEcxOGFuUEowUittbEF2VmJm
            emFBRmhmY01BY2xDbFRKd2Z3YVVNMGNlb3VSRHNXMXl3VHdPb0swNW96YgpJYVJydC8vaWRKeS8w
            Y0dUN2Y2RHVDWlVOMzE5T1BncjZWOU5JMU85bFVKbHJydVo1TVZsTGRSdytqNThtWHZVCjlzaVlj
            WE1xMzR3TkFqTGRGRlVWUnFOZElpM3NTSHhrK2FVWUVkb05yUU1YQWFhNHZCMUNGL1pEZGdkQ2Jj
            dWcKVmJWTnM2UTFFTTFBYk9QNEhuZ2kxVHVCZTFmWTNVM2ljTkRseW56RHZTMXNEMCtkRHhWeGpI
            MzBCTm9zVCtSYworZGxoRWVFb1pnZDU3NWtkU0xuR21CU0hvUjJoL2RxOXpqa0lnSlp0Y2x0YkJv
            ejNtcjhFdlpsdW5hcHlwQWdMCm45Z21yRjJmQWdNQkFBRUNnZ0VBZktsY2RaSUY0dCtjRktkRjdi
            cjhzbFlUWkhLODFSSGZxbVlsVEordHFCQ0QKNkhwMk9tQlJWamR1TC9oUjNJSGdUWFMwZkV3L1I1
            V3gxWXloaEtpdFhxTUhhQm81M3FjYUNDQTNuWGFkYTl5Qgo1S0x2ek92M3ZtbU96MGlvOFJoUUYz
            MlRycDdXTFo2dFhqQm1TQnBDdGVMOUFOZk9EQ2dRaVd5VWxPUFoxY2hwCmxGTXVmSmZadDRSTjNS
            Ykl5aXkzS05yV2pHZHF5K0M2MnJIYVl2eTdwWjNwYVhXb1RlRU5LbkU1bjRFRzhnZjYKaFoyZ2ZH
            RW5ER2NSbEhEVXd0UGNreWhGcmVudGdkbHo2cWNlM3o0SFcxVnAvRFhWQkVNUnhnMlowcDRvcXJ6
            YwpqMEoxQmtVNk96NFhNdWM4MldJTXhqYXhGMkRWUmk1S3U0bDVyUzR4MlFLQmdRRGk1cFNqWWdS
            eGJnTXlCWUl3ClhPZjA1RWYva0cvaDhBZURNUkd3WGtIcXlwTkM2aks1Q3VveE5neVgyOFM2MFRa
            Umo2RVlkeXp2RjE5M1NUYy8KaXg3VU5BSWhWeG5KMEhKbitQdVl5MjJtdE5EQ0ovNGZDQWRrcC9C
            S2kyQS9jQlhoVFp3bzMvMHBoMm9KSnNLcwpmTlE3bkduZmcybVpHZGRXR01zc1MzbnZ1d0tCZ1FE
            NUNqaE9oVExxSnpTa1RWZC83S3VjWkw0aFV1NzNuWnpiCkhCT0JwNUUzczZScExUWkM4WjhUQWFD
            WlorY3hFN0hGZzF0eVZ5RXFFS3NOUUsrUXVkM1ZYU0VQTWdiUFdHdkoKa0dXUzl0NEdlTGsvaHRQ
            NE5pSzJoRk5CckhjRDRqUXIyRVNSMWw4VktxUlFBdjB5OE1yTTZnV1dxLzUrdXlYcwo0cGluekhP
            eGJRS0JnQi9uYWhqN0RFTGl4Q0pCY2dmWTJHaXZ2SXZyeEQrUm40ekwxbi9sRVFHeGtEbEZjdkpm
            CjNZUWo1R3RwNUdTY1REWDFxeUlraDdYcXBHckNhYmxPbDN3Zy8vZXVKcHNnNnlWQmRpY0syNVVv
            TVg1TFgwai8KdVFKbk5ydFVrNmozMnF1K1hPbkdiUE5zN2ZUeGRVZ0ptVkgwY1ZLVFNNTFZSbGo5
            elh1aDlUaEhBb0dCQU40KwpEWk9jOEp2ZlV1NFJDelhoQ2lDdUVyS0FaVHRhVDJHRnc2NmYwRXNx
            S0YybitGVnpkS2NzZTVxTEM5bFRId0VKClFYRmZhZncxRmNEazZnZzRwa3ZES1Q1N1FYS0dFT0sy
            MXI1NVNoZnlZamJiNW93S0c1NVBwbERrVE8yTlQwdVYKVzFQZVA4b08zTVYrZFdDaFhBblVDaHEw
            OEk4K0NoRkZBa0EwaDBaZEFvR0FISXpOamp4UVhKOHlRRkUrWXp3ZApRUU12M3N1WmF6ZmJYUDk1
            VHF4cVJmMlBXU0tkSlhvUG15am92OUJsd1lwRzJESDdBdGJOYzhBOXFBRisycVBRCnAxRTdsb0Vj
            aUk0Z1NCcEdsTU9OKzhDanpoR2dvcXVyZzVIUnByaGlWQ2EyMXRZSzBTcGlmTEQ3NFhTaS9oSEQK
            M3BycUJOWjQzekpOTmo4NHozcXJZMjQ9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls